### PR TITLE
Kde supports screencast portal

### PR DESCRIPTION
**Pull request by worldofpeace**
See https://github.com/KDE/xdg-desktop-portal-kde/blob/5f64fb5bbd4e96633e61c406795e0ea23e11c09f/src/screencast.cpp

### CODE REVIEW

**Comment by cassidyjames** [comment]
@worldofpeace we need to be more clear about what we're showing support for here; we're really interested in whether or not the desktop shows a visual indication that the portal is being used. Do you know if that's the case?

**Comment by worldofpeace** [comment]
I'll quote one of their release notes
> https://kde.org/announcements/plasma-5.13.0.php
> Our compositor KWin gained much-improved effects for blur and desktop switching. Wayland work continued, with the return of window rules, the use of high priority EGL Contexts, and initial support for screencasts and desktop sharing.
> xdg-desktop-portal-kde, used to give desktop integration for Flatpak and Snap applications, gained support for screenshot and screencast portals.

That was over a year ago when the initial feature was added. I have every reason to believe, since they mentioned both these things in their notes, that it supports this.

**Comment by worldofpeace** [comment]
Also, I'm not sure what you mean by "be more clear about what we're showing support for here".
I've interpreted this as explain further to you @cassidyjames.

**Comment by cassidyjames** [comment]
@worldofpeace sorry, no, I meant the site needs to be more clear about what we mean in this Portals section. See #3, which supersedes this. Do you know if KDE shows a _visual indication to the user_ when the screencast portal is in use?

**Comment by worldofpeace** [comment]
@cassidyjames Ah, now understand :+1: . And no, I'm not sure whether a visual indication is shown when it is in use. I'd start a vm to check, but in my particular distro pipewire support is to be determined. So that much we can't assume.

I'll close this as you've superseded with https://github.com/islinuxabout/islinuxabout.github.io/pull/3, and appears to include at least part of this.

**Pull request closed without merging**
